### ISSUE TITLE
Solana: port transaction submission API from web3.js

### ISSUE THREAD

**Issue by mschneider** [mschneider/solcpp#40]
[requestAirdrop](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#requestAirdrop)
[confirmTransaction](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#confirmTransaction)
[sendEncodedTransaction](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#sendEncodedTransaction)
[sendRawTransaction](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#sendRawTransaction)
[sendTransaction](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#sendTransaction)
[simulateTransaction](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#simulateTransaction)

**Comment by aniketfuryrocks** [comment]
Willing to work on this

**Comment by Lioncat2002** [comment]
Willing to work on this as well

**Comment by Lioncat2002** [comment]
@mschneider 
Added the `requestAirdrop` function
I have two questions before I create a new PR
1. How do I write a new test
Since the hash that that gets returned by the rpc client changes everytime
There isn't really anything that can be compared to check if the test passed.
2. The `rpc_url_` that you seem to be using in all the post request is set to the main net which doesn't have the `requestAirdrop` method
So, should I set the post `requestAirdrop` url to `devnet` or `testnet`?

**Comment by mschneider** [comment]
requestAidrop should increase the sol balance of the wallet

**Comment by mschneider** [comment]
you can specify devnet url when creating the Connection object

**Comment by mschneider** [comment]
@Lioncat2002 @aniketfuryrocks 

I noticed that the new methods return `json` as response type. Please make sure you parse the json responses and created proper types for them, similar to what [web3.js](https://solana-labs.github.io/solana-web3.js/) does. This will help users of the API to leverage type based auto completion to use the library more efficiently.

**Comment by aniketfuryrocks** [comment]
- Added (Serialize json returns to structs) as a part of #43
